POST http://localhost:3000/api/table/master/categories/ HTTP/1.1
Content-Type: application/json

{
    "name": "livres"
}

###

GET http://localhost:3000/api/table/master/tasks/clgxxcmxw0000zk7v5nlrdvmh HTTP/1.1

###

PATCH  http://localhost:3000/api/table/master/tasks/clgxxcmxw0000zk7v5nlrdvmh HTTP/1.1
Content-Type: application/json

{
    "description": "ça c'est fait"
}

###

GET http://localhost:3000/api/table/master/tasks HTTP/1.1

###

DELETE http://localhost:3000/api/table/master/tasks/7114cf09-294c-4306-a2c4-518bce6b9deb HTTP/1.1

###