POST http://localhost:3000/api/table/master/categories/ HTTP/1.1
Content-Type: application/json

{
    "name": "films",
    "description": "films à voir"
}

###

GET http://localhost:3000/api/table/master/categories HTTP/1.1

###

PATCH  http://localhost:3000/api/table/master/categories/clh6joi290000zkhn4v0rljot HTTP/1.1
Content-Type: application/json

{
    "description": "films d'horreurs"
}

###

GET http://localhost:3000/api/table/master/tasks HTTP/1.1

###

DELETE http://localhost:3000/api/table/master/tasks/7114cf09-294c-4306-a2c4-518bce6b9deb HTTP/1.1

###