POST http://localhost:3001/api/table/tasks/ HTTP/1.1
Content-Type: application/json

{
    "task": "faire ça",
    "done": true
}

###

GET http://localhost:3001/api/table/users/92539185-cd23-4bd7-b5de-c698d4a2f27c HTTP/1.1

###

PATCH  http://localhost:3001/api/table/users/92539185-cd23-4bd7-b5de-c698d4a2f27c HTTP/1.1
Content-Type: application/json

{
    "name": "Thomas JEANNEAU !"
}

###

GET http://localhost:3001/api/table/users HTTP/1.1

###

DELETE http://localhost:3001/api/table/users/92539185-cd23-4bd7-b5de-c698d4a2f27c HTTP/1.1

###