export type Name = SansSerif | Serif;

export type SansSerif = 
  | 'Roboto'
  | 'Open Sans'
  | 'Lato'
  | 'Montserrat'
  | 'Raleway'
  | 'PT Sans'
  | 'Noto Sans'
  | 'Ubuntu'
  | 'Merriweather Sans'
  | 'Work Sans'
  | 'Nunito Sans'
  | 'Poppins'
  | 'Source Sans Pro'
  | 'IBM Plex Sans'
  | 'Rubik'
  | 'Fira Sans'
  | 'Hind'
  | 'Karla'
  | 'Asap'
  | 'Barlow'
  | 'Heebo'
  | 'Catamaran'
  | 'Manrope'
  | 'Inter'
  | 'Mulish'
  | 'Exo 2'
  | 'Josefin Sans'
  | 'Questrial'
  | 'Titillium Web'
  | 'Mukta'
  | 'Varela Round'
  | 'Lexend Deca'
  | 'Public Sans'
  | 'Space Grotesk';

export type Serif = 
  | 'Roboto Slab'
  | 'Merriweather'
  | 'Lora'
  | 'Playfair Display'
  | 'Slabo 27px'
  | 'Noto Serif'
  | 'PT Serif'
  | 'Libre Baskerville'
  | 'Bitter'
  | 'Alegreya'
  | 'Cormorant Garamond'
  | 'Domine'
  | 'EB Garamond'
  | 'Crimson Text'
  | 'Zilla Slab'
  | 'Tinos'
  | 'Cardo'
  | 'Neuton'
  | 'Bree Serif'
  | 'Faustina'
  | 'Frank Ruhl Libre'
  | 'Lusitana'
  | 'Cormorant'
  | 'Inknut Antiqua'
  | 'Gentium Basic'
  | 'Maitree'
  | 'Spectral';
