POST http://localhost:3000/api/table/invoices/ HTTP/1.1
Content-Type: application/json

{
    "name": "Facture 1002",
    "amount": 26030
}

###

GET http://localhost:3000/api/table/master/tasks HTTP/1.1

###

PATCH  http://localhost:3000/api/table/invoices/cliiqkeao0000wvsyxeymc6xh HTTP/1.1
Content-Type: application/json

{
    "status": "sent",
    "amount": 50
}

###

GET http://localhost:3000/api/table/master/tasks HTTP/1.1

###

DELETE http://localhost:3000/api/table/master/categories/clhhklwiv0000zkzoozhtmmsu HTTP/1.1

###