export type Icon =
  | 'Cog'
  | 'ChartBarSquare'
  | 'Scale'
  | 'Cog6Tooth'
  | 'Banknotes'
  | 'ChatBubbleLeftEllipsis'
  | 'FaceSmile'
  | 'ComputerDesktop'
  | 'DevicePhoneMobile'
  | 'CommandLine'
  | 'MagnifyingGlass'
  | 'AcademicCap'
  | 'ChatBubbleBottomCenterText'
  | 'Home'
  | 'Users'
