// This file is generated by the DatabaseUtils.buildImport() method.

import SystemsPrismaClients from '../../../../../apps/systems/js/prisma'
// End import

let PrismaClients = {}

function exportPrismaClients(appName: string, clients: object) {
  if (process.env.APP_NAME === appName) {
    PrismaClients = clients
  }
}

exportPrismaClients('systems', SystemsPrismaClients)
// End export

export { PrismaClients }
