/**
 * This file is generated by the DatabaseUtils.buildImport() method.
 */

/** Start import */
import SystemsPrismaClients from '/Users/thomasjeanneau/Codes/Essentiel/foundation/apps/systems/js/prisma'
/** End import */

let PrismaClients = {}

function exportPrismaClients(appName: string, clients: object) {
  if (process.env.APP_NAME === appName) {
    PrismaClients = clients
  }
}

/** Start export */
exportPrismaClients('systems', SystemsPrismaClients)
/** End export */

export { PrismaClients }
